<?php
$securitySettings_var = array( 'providers' => array( array( 'active' => true,
'code' => '00',
'label' => array( 'text' => 'Hardcoded',
'type' => 0 ),
'name' => 'hardcoded',
'password' => 'admin',
'type' => '%hardcoded',
'username' => 'admin' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'PLhGie5niPdNx4kj71NB',
'JWTSecret' => 'Am9TEgUsf1peVtOmQ0Lt' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'registerPage' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => '',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'localhost',
'SMTPPort' => 25,
'SMTPUser' => '',
'SMTPPassword' => '',
'securityProtocol' => 0 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array(  ),
'lockingTable' => array(  ),
'tables' => array(  ),
'loggingMode' => 0,
'loggingFile' => 'audit.log',
'logSecurityActions' => false,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'Projeto de Desenvolvimento de Sistemas',
'loginDataSource' => 'Projeto de Desenvolvimento de Sistemas_Usuarios',
'loginForm' => 1,
'dynamicPermissions' => false,
'dpTablePrefix' => 'Projeto de Desenvolvimento de Sistemas',
'dpTableConnId' => 'ProjetodeDesenvolvimentodeSist',
'hardcodedLogin' => true,
'enabled' => true,
'advancedSecurityAvailable' => false,
'userGroupsAvailable' => false,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'hardcodedProvider' => array( 'active' => true,
'code' => '00',
'label' => array( 'text' => 'Hardcoded',
'type' => 0 ),
'name' => 'hardcoded',
'password' => 'admin',
'type' => '%hardcoded',
'username' => 'admin' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array(  ) );
?>